[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="classInfo" type="io.github.ourongbin.dev.codegen.ClassInfo" --]
[#-- @ftlvariable name="tableName" type="java.lang.String" --]
[#-- @ftlvariable name="CapClassName" type="java.lang.String" --]
[#-- @ftlvariable name="className" type="java.lang.String" --]
[#-- @ftlvariable name="baseUrl" type="java.lang.String" --]
[#-- @ftlvariable name="packageName" type="java.lang.String" --]
[#-- @ftlvariable name="returnUtil" type="java.lang.String" --]
[#-- @ftlvariable name="pageRequest" type="java.lang.String" --]
[#-- @ftlvariable name="pageResponse" type="java.lang.String" --]
[#-- @ftlvariable name="bizException" type="java.lang.String" --]
[#-- @ftlvariable name="fullReturnUtil" type="java.lang.String" --]
[#-- @ftlvariable name="fullPageRequest" type="java.lang.String" --]
[#-- @ftlvariable name="fullPageResponse" type="java.lang.String" --]
[#-- @ftlvariable name="fullBizException" type="java.lang.String" --]
[#-- @ftlvariable name="swagger" type="boolean" --]
